### ISSUE TITLE
HTTP Authentication / Sync with custom server

### ISSUE THREAD

**Issue by bastei** [graetzer/Foxbrowser#11]
While trying to get firefox synced with a custom sync server foxbrowser doesn't send any credentials via HTTP Basic Authentication.

The server is the ownCloud App [mozilla_sync](https://github.com/owncloud/mozilla_sync), which expects HTTP Basic Authentication like it is suggested by the [Mozilla Sync Specification](http://docs.services.mozilla.com/sync/overview.html#the-sync-server). It returns 401 as the user can't be authenticated.
There is also an issue in the owncloud/mozilla_sync repo for this problem (https://github.com/owncloud/mozilla_sync/issues/24) but it looks like the problem is actually on the foxbrowser's site.

Activating "HTTP Authentication" in the Settings of foxbrowser does not solve the problem.

Can you explain how foxbrowser is authenticating the user? Or is it a bug? Or did I miss anything?

**Comment by graetzer** [comment]
Foxbrowser is based on the code of the Firefox Home App: https://github.com/mozilla-services/ios-sync-client
Either this is a new bug or the bug was in the original code.

Have you tried syncing your owncloud installation with a different app that uses the same codebasis as Foxbrowser? There is a free App which looks like a re-branded version of Firefox Home: https://itunes.apple.com/de/app/bookmarks-on-the-go/id550037184?mt=8

Also the settings option "HTTP Authentication" shouldn't affect the way sync works.
It allows to use HTTP auth to login into webpages with the browser. This is normally not possible with the iOS web-view component.

**Comment by graetzer** [comment]
Doesn't apply to the current version anymore

**Comment by seizu** [comment]
Unfortunately, HTTPBasic Auth does not work at all. Page loading hangs and no login request appears. 

Test page:
http://httpbin.org/basic-auth/user/passwd

**Comment by graetzer** [comment]
Have you tried turning it on in the settings?

**Comment by seizu** [comment]
My bad, I had overlooked it.
Btw, great work :+1:
