### ISSUE TITLE
Unable to load webpages/sync with selfsigned certificats

### ISSUE THREAD

**Issue by jwacalex** [graetzer/Foxbrowser#7]
Hi,
if i want to visit a server secured by an self-signed ssl-certifcate, the browser shows an error that I can't visit the page. it shows the same behaviour if want to sync with an server secured by such a certificate (unable to connect).
adding the certificate to safari doesn't solve this problem

**Comment by graetzer** [comment]
Yes this is an UIWebView issue, you should be able to avoid it by activating HTTP Authentication in the Foxbrowser settings.
I won't enable syncing with a server with a self-signed ssl-certifcate, this is just unsecure

**Comment by jwacalex** [comment]
Just a question out of curiosity: Why should the activation of HTTP-Auth allow me to open a page with a self-signed certificate? anyway it resolved this part of the bug

I can't understand why using a sync-server with a self-signed certificate is more secure than a one with a signed one by a root ca. if i know what certificate i accept i can validate it by the checksum. otherwise i've to trust e.g. diginotar that everything is ok.

**Comment by graetzer** [comment]
Because the accurate name of the option would be "Enable custom network stack", but then I would have to explain what that means. Maybe I'll rename it to 'Enable unsecure certicates', that use-case is actually more common.

A certificate that you signed yourself may be secure for you, but you are an experienced user while most other people are not. If I'll build in an UI option that would ask the users in case of an self signed certificate, 95% of the users would click yes, because they have no idea what that means. 
I could build an hidden option for advanced user, but to be honest, personally I don't need this and 99,8% of my users don't care.

But to give you some hope: In a few months mozilla is planning to introduce an entirely new sync API and a complete rewrite of my code is inevitable. I'll probably spend most of my summer break doing this and I might build in some advanced options as well

**Comment by stonie08** [comment]
I have the same issue with self-signed certificates, but for me activating the HTTP Authentication option didn't resolve this problem. (Is it using port 80 after activating this? Port 80 is closed for security reasons which would explain why it doesn't work either)
Any ideas to rid of it?

Besides I wouldn't say syncing with a self-signed certificate is insecure. There should be a similar behaviour as when using foxbrowser to navigate to a side with a self-signed SSL certificate which additionally displays an MD5 and SHA1 and than allows you decide, Maybe some really scary warning would be nice in case the sync servers certificate changes. And that's it.

**Comment by graetzer** [comment]
I wasn't saying this issue isn't valid, I just don't have the time to do anything about it. 
The syncing code is (in my opinion) an ugly mess (It wasn't written by me) and with the release of iOS 7 there are more pressing things that require attention

The port should be included in the URL, I don't think that's an issue

**Comment by stonie08** [comment]
@jwacalex If you still have this issue I think I figured out some kind of workaround for this. Simply download the "iPhone Configuration Utility" from Apple. With this application you can import your self signed certificate as a profile for iOS. It seams that this utility signs this certificate for your, or at least marks it as a verified certificate signed by some kind of "iPCU CA". However your certificate will be installed as a profile and therefore be valid for all applications that use it, including Foxbrowser and enables syncing with foxbrowser over HTTPS.
